---
title: "Sales Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
resource_files:
- bikes_tbl.rds
- bikeshops_tbl.rds
- gadm36_DEU_1_sp.rds
- orderlines_tbl.rds
- plot_sales.R
---

```{r setup, include=FALSE}
options(encoding = "UTF-8")
library(flexdashboard)

# Core
library(tidyverse)

# Interactive Visualizations
library(plotly)

# Spatial Data
library(raster)
library(sf)
library(shiny)
library(shinyWidgets)
library(rgeos)


# Currency formatting
 source("plot_sales.R")
```

```{r}
# Bike data
#rmarkdown::run('~/DataS/DS ML/data_products-sachdva/flexdashboard.Rmd')
#load data
bikes_tbl      <- readRDS("bikes_tbl.rds")
bikeshops_tbl  <- readRDS("bikeshops_tbl.rds")
orderlines_tbl <- readRDS("orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
    left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
    mutate(total_price = price_euro * quantity)
# German spatial data
germany_sp <- getData('GADM', country='DE', level=1) 
germany_sf <- st_as_sf(germany_sp) %>% 
  
                  # Add english names
                  mutate(VARNAME_1 = ifelse(is.na(VARNAME_1), NAME_1, VARNAME_1)) 



```

Sidebar {.sidebar}
------------------------

```{r}
#make the dataRange input
dateRangeInput(inputId = "date_range", 
               label   = h4("Date Range"), 
               start   = min(bike_orderlines_tbl$order_date), 
               end     = max(bike_orderlines_tbl$order_date),
               min     = min(bike_orderlines_tbl$order_date), 
               max     = max(bike_orderlines_tbl$order_date), 
               startview = "year")

# Make the biketype Input
checkboxGroupInput(inputId = "bike_type", 
                   label   = h4("Bike Type"), 
                   choices = c(distinct(bike_orderlines_tbl, category_1)$category_1),
                   selected = c(distinct(bike_orderlines_tbl, category_1))$category_1)
# Make the Bike family dropdown Input
pickerInput(
  inputId = "bike_family",
  label = "Bike Family",
  choices = c(distinct(bike_orderlines_tbl, category_2)$category_2),
  selected = c(distinct(bike_orderlines_tbl, category_2)$category_2),
  options = list(
    `actions-box` = TRUE,
    size = 10,
    `selected-text-format` = "count > 3"
  ),
  multiple = TRUE
)
#the allmighty apply button
actionButton(inputId = "apply", 
             label   = "Apply", 
             icon    = icon("play"))
# Reset Button
actionButton(inputId = "reset", 
             label   = "Reset", 
             icon    = icon("sync"))

```


```{r}
# The real work observing events


#reset, pretty simple just reset all to base values
observeEvent(eventExpr = input$reset, handlerExpr = {

  updateCheckboxGroupInput(session  = session, 
                           inputId  = "bike_type", 
                           selected = c(distinct(bike_orderlines_tbl, category_1))$category_1)
  
  updateDateRangeInput(session = session, 
                       inputId = "date_range", 
                       start   = min(bike_orderlines_tbl$order_date), 
                       end     = max(bike_orderlines_tbl$order_date))
  
  updatePickerInput(session = session, 
                    inputId = "bike_family", 
                    selected = c(distinct(bike_orderlines_tbl, category_2)$category_2))
  
})

## THE BIG FUNCTION APPLY
observeEvent(eventExpr = input$apply, handlerExpr = {
  #browser() This function was used to debug lol a lot
  bikes <- bike_orderlines_tbl %>% 
                  filter(category_1 %in% input$bike_type)  %>%
                  filter(category_2 %in% input$bike_family) %>%
                  filter(order_date >= input$date_range[1]) %>%
                  filter(order_date <= input$date_range[2])
  
  geo_plot_tbl <- bikes %>% 
                  group_by(state) %>%
                  summarise(total_revenue = sum(total_price)) %>%
                  ungroup() %>%
                  right_join(germany_sf, by = c("state" = "VARNAME_1")) %>% 
                  mutate(total_revenue = ifelse(is.na(total_revenue), 0, total_revenue)) %>% 
                  mutate(label_text = str_glue("State: {state}
                                         Revenue: {format_to_euro(total_revenue)}")) %>% 
                  # Convert back to an sf object, that can be plotted
                  st_as_sf()
  #browser()
  mapg <- plot_ly(geo_plot_tbl, 
        split      = ~NAME_1, 
        color      = ~total_revenue,
        colors     = "Blues",
        stroke     = I("black"),
        hoverinfo  = 'text', 
        text       = ~label_text, 
        hoveron    = "fills", 
        showlegend = FALSE) 

  output$output_states <- renderPlotly(mapg) 
  #browser()
  ratio <- count(bikes %>% filter(category_1 == "Mountain")) /
    count(bikes %>% filter(category_1 == "Road"))
  #browser()
  output$orders <- renderValueBox({
    valueBox(count(bikes  %>% distinct(distinct_values = order_id)), "Order", icon ="fa-heartbeat", color = "bg-success")
  })

  output$tsales <- renderValueBox((
    valueBox(format_to_euro(sum(bikes$total_price)), "Sales", icon ="fa-money-check-alt", color="bg-primary")
  ))

  output$ratio <- renderValueBox((
    valueBox(as.numeric(round(ratio, digits=1)), "Ratio, Mountain to Road", icon ="fa-brain", color="bg-info")))


  sales <- plot_total_sales_f(bikes, unit = "month", date_format = "%B %Y", interactive = TRUE)
  output$output_sales <- renderPlotly(sales)
  
})



# filter based on time units
#day
observeEvent(eventExpr = input$day, handlerExpr = {
  bikes <- bike_orderlines_tbl %>% 
                  filter(category_1 %in% input$bike_type)  %>%
                  filter(category_2 %in% input$bike_family) %>%
                  filter(order_date >= input$date_range[1]) %>%
                  filter(order_date <= input$date_range[2])
  sales <- plot_total_sales_f(bikes,unit = "day", date_format = "%B %d, %Y", interactive = TRUE)
  output$output_sales <- renderPlotly(sales)
})
#week
observeEvent(eventExpr = input$week, handlerExpr = {
  bikes <- bike_orderlines_tbl %>% 
                  filter(category_1 %in% input$bike_type)  %>%
                  filter(category_2 %in% input$bike_family) %>%
                  filter(order_date >= input$date_range[1]) %>%
                  filter(order_date <= input$date_range[2])
  sales <- plot_total_sales_f(bikes,unit = "week", date_format = "%B %d, %Y", interactive = TRUE)
  output$output_sales <- renderPlotly(sales)
})
#month
observeEvent(eventExpr = input$month, handlerExpr = {
  bikes <- bike_orderlines_tbl %>% 
                  filter(category_1 %in% input$bike_type)  %>%
                  filter(category_2 %in% input$bike_family) %>%
                  filter(order_date >= input$date_range[1]) %>%
                  filter(order_date <= input$date_range[2])
  sales <- plot_total_sales_f(bikes,unit = "month", date_format = "%B %Y", interactive = TRUE)
  output$output_sales <- renderPlotly(sales)
})
#quarter
observeEvent(eventExpr = input$quarter, handlerExpr = {
  bikes <- bike_orderlines_tbl %>% 
                  filter(category_1 %in% input$bike_type)  %>%
                  filter(category_2 %in% input$bike_family) %>%
                  filter(order_date >= input$date_range[1]) %>%
                  filter(order_date <= input$date_range[2])
  sales <- plot_total_sales_f(bikes,unit = "quarter", date_format = "%B %Y", interactive = TRUE)
  output$output_sales <- renderPlotly(sales)
})
#year
observeEvent(eventExpr = input$year, handlerExpr = {
  bikes <- bike_orderlines_tbl %>% 
                  filter(category_1 %in% input$bike_type)  %>%
                  filter(category_2 %in% input$bike_family) %>%
                  filter(order_date >= input$date_range[1]) %>%
                  filter(order_date <= input$date_range[2])
  sales <- plot_total_sales_f_y(bikes,unit = "year", date_format = "%Y", interactive = TRUE)
  output$output_sales <- renderPlotly(sales)
})
```

Row {data-height=150}
-------------------------------------

### Orders

```{r}
valueBoxOutput("orders")

output$orders <- renderValueBox({
    valueBox(0, "Order", icon ="fa-heartbeat", color="bg-success")
  })

```

### Sales

```{r}
valueBoxOutput("tsales")

output$tsales <- renderValueBox({valueBox(0, "Sales", icon ="fa-money-check-alt", color="bg-primary")
  })

```   
    
### Ratio, Mountain to Road

```{r}
valueBoxOutput("ratio")

output$ratio <- renderValueBox({valueBox(0, "Ratio, Mountain to Road", icon ="fa-brain", color="bg-info")
  })

```

Row {data-height=850}
---------------------------------------------------------------

### By State

```{r}
plotlyOutput("output_states")
```

### Over Time
Time Unit

```{r}
actionButton(inputId = "day", 
             label   = "D")

actionButton(inputId = "week", 
             label   = "W")

actionButton(inputId = "month", 
             label   = "M")

actionButton(inputId = "quarter", 
             label   = "Q")

actionButton(inputId = "year", 
             label   = "Y")
```

```{r}
plotlyOutput("output_sales")
```